serve:
  proxy:
    port: 4455 # run the proxy at port 4455
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_headers:
        - Authorization
        - Content-Type
        - method
      exposed_headers:
        - Authorization
        - Content-Type
        - method
  api:
    port: 4456 # run the api at port 4456
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_headers:
        - Authorization
        - Content-Type
        - x_method
      exposed_headers:
        - Authorization
        - Content-Type
        - x_method

access_rules:
  repositories:
    - file:///rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://192.168.124.18:4445/oauth2/introspect
authorizers:
  allow:
    enabled: true
  remote:
    # Set enabled to "true" to enable the authenticator, and "false" to disable the authenticator. Defaults to "false".
    enabled: false
    config:
      remote: http://192.168.124.18:4000/authz/permission/allow
      headers:
        x-client-id: "{{ print .Extra.client_id }}"
        x-origin-url: "{{ print .MatchContext.URL}}"
        x-method: "{{ print .Header.x_method}}"

  remote_json:
    enabled: true
mutators:
  noop:
    enabled: true
  header:
    # Set enabled to true if the authenticator should be enabled and false to disable the authenticator. Defaults to false.
    enabled: true
    config:
      headers:
        x_method: '{{ print .Header }}'